import React, { useState, useEffect } from "react";

// Comprehensive emoji database with tags for better searching
const EMOJI_DATABASE = {
  // Faces & People
  faces: {
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "🤣",
      "😂",
      "🙂",
      "🙃",
      "🫠",
      "😉",
      "😊",
      "😇",
      "🥰",
      "😍",
      "🤩",
      "😘",
      "😗",
      "☺️",
      "😚",
      "😙",
      "🥲",
      "😋",
      "😛",
      "😜",
      "🤪",
      "😝",
      "🤑",
      "🤗",
      "🤭",
      "🫢",
      "🫣",
      "🤫",
      "🤔",
      "🫡",
      "🤐",
      "🤨",
      "😐",
      "😑",
      "😶",
      "🫥",
      "😏",
      "😒",
      "🙄",
      "😬",
      "🤥",
      "😔",
      "😪",
      "🤤",
      "😴",
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🤧",
      "🥵",
      "🥶",
      "🥴",
      "😵",
      "🤯",
      "🤠",
      "🥳",
      "🥸",
      "😎",
      "🤓",
      "🧐",
      "😕",
      "😟",
      "🙁",
      "☹️",
      "😮",
      "😯",
      "😲",
      "😳",
      "🥺",
      "😦",
      "😧",
      "😨",
      "😰",
      "😥",
      "😢",
      "😭",
      "😱",
      "😖",
      "😣",
      "😞",
      "😓",
      "😩",
      "😫",
      "🥱",
      "😤",
      "😡",
      "😠",
      "🤬",
      "😈",
      "👿",
      "💀",
      "☠️",
      "💩",
      "🤡",
      "👹",
      "👺",
      "👻",
      "👽",
      "👾",
      "🤖",
      "😺",
      "😸",
      "😹",
      "😻",
      "😼",
      "😽",
      "🙀",
      "😿",
      "😾",
    ],
    tags: [
      "face",
      "emotion",
      "happy",
      "sad",
      "angry",
      "surprised",
      "love",
      "laugh",
      "smile",
      "cry",
    ],
  },

  // People & Body
  people: {
    emojis: [
      "👶",
      "🧒",
      "👦",
      "👧",
      "🧑",
      "👱",
      "👨",
      "🧔",
      "👩",
      "🧓",
      "👴",
      "👵",
      "🙍",
      "🙎",
      "🙅",
      "🙆",
      "💁",
      "🙋",
      "🧏",
      "🙇",
      "🤦",
      "🤷",
      "👮",
      "🕵️",
      "💂",
      "🥷",
      "👷",
      "🫅",
      "🤴",
      "👸",
      "👳",
      "👲",
      "🧕",
      "🤵",
      "👰",
      "🤰",
      "🫃",
      "🫄",
      "🤱",
      "👼",
      "🎅",
      "🤶",
      "🦸",
      "🦹",
      "🧙",
      "🧚",
      "🧛",
      "🧜",
      "🧝",
      "🧞",
      "🧟",
      "🧌",
      "💆",
      "💇",
      "🚶",
      "🧍",
      "🧎",
      "🏃",
      "💃",
      "🕺",
      "🕴️",
      "👯",
      "🧖",
      "🧗",
      "🤺",
      "🏇",
      "⛷️",
      "🏂",
      "🏌️",
      "🏄",
      "🚣",
      "🏊",
      "⛹️",
      "🏋️",
      "🚴",
      "🚵",
      "🤸",
      "🤼",
      "🤽",
      "🤾",
      "🤹",
      "🧘",
      "🛀",
      "🛌",
    ],
    tags: [
      "person",
      "people",
      "human",
      "man",
      "woman",
      "child",
      "baby",
      "activity",
      "sport",
      "job",
      "profession",
    ],
  },

  // Animals & Nature
  animals: {
    emojis: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐻‍❄️",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐽",
      "🐸",
      "🐵",
      "🙈",
      "🙉",
      "🙊",
      "🐒",
      "🐔",
      "🐧",
      "🐦",
      "🐤",
      "🐣",
      "🐥",
      "🦆",
      "🦅",
      "🦉",
      "🦇",
      "🐺",
      "🐗",
      "🐴",
      "🦄",
      "🐝",
      "🪱",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🐜",
      "🪰",
      "🪲",
      "🪳",
      "🦟",
      "🦗",
      "🕷️",
      "🕸️",
      "🦂",
      "🐢",
      "🐍",
      "🦎",
      "🦖",
      "🦕",
      "🐙",
      "🦑",
      "🦐",
      "🦞",
      "🦀",
      "🐡",
      "🐠",
      "🐟",
      "🐬",
      "🐳",
      "🐋",
      "🦈",
      "🐊",
      "🐅",
      "🐆",
      "🦓",
      "🦍",
      "🦧",
      "🐘",
      "🦛",
      "🦏",
      "🐪",
      "🐫",
      "🦒",
      "🦘",
      "🐃",
      "🐂",
      "🐄",
      "🐎",
      "🐖",
      "🐏",
      "🐑",
      "🦙",
      "🐐",
      "🦌",
      "🐕",
      "🐩",
      "🦮",
      "🐕‍🦺",
      "🐈",
      "🐈‍⬛",
      "🪶",
      "🐓",
      "🦃",
      "🦚",
      "🦜",
      "🦢",
      "🦩",
      "🕊️",
      "🐇",
      "🦝",
      "🦨",
      "🦡",
      "🦫",
    ],
    tags: [
      "animal",
      "pet",
      "wild",
      "nature",
      "mammal",
      "bird",
      "fish",
      "insect",
      "reptile",
      "marine",
    ],
  },

  // Food & Drink
  food: {
    emojis: [
      "🍎",
      "🍏",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🫐",
      "🍈",
      "🍒",
      "🍑",
      "🥭",
      "🍍",
      "🥥",
      "🥝",
      "🍅",
      "🍆",
      "🥑",
      "🥦",
      "🥬",
      "🥒",
      "🌶️",
      "🫑",
      "🌽",
      "🥕",
      "🫒",
      "🧄",
      "🧅",
      "🥔",
      "🍠",
      "🥐",
      "🥖",
      "🍞",
      "🥨",
      "🥯",
      "🥞",
      "🧇",
      "🧀",
      "🍖",
      "🍗",
      "🥩",
      "🥓",
      "🍔",
      "🍟",
      "🍕",
      "🌭",
      "🥪",
      "🌮",
      "🌯",
      "🫔",
      "🥙",
      "🧆",
      "🥚",
      "🍳",
      "🥘",
      "🍲",
      "🫕",
      "🥣",
      "🥗",
      "🍿",
      "🧈",
      "🧂",
      "🥫",
      "🍱",
      "🍘",
      "🍙",
      "🍚",
      "🍛",
      "🍜",
      "🍝",
      "🍠",
      "🍢",
      "🍣",
      "🍤",
      "🍥",
      "🥮",
      "🍡",
      "🥟",
      "🥠",
      "🥡",
      "🦀",
      "🦞",
      "🦐",
      "🦑",
      "🦪",
      "🍦",
      "🍧",
      "🍨",
      "🍩",
      "🍪",
      "🎂",
      "🍰",
      "🧁",
      "🥧",
      "🍫",
      "🍬",
      "🍭",
      "🍮",
      "🍯",
      "🍼",
      "🥛",
      "☕",
      "🫖",
      "🍵",
      "🍶",
      "🍾",
      "🍷",
      "🍸",
      "🍹",
      "🍺",
      "🍻",
      "🥂",
      "🥃",
      "🥤",
      "🧋",
      "🧃",
      "🧉",
      "🧊",
    ],
    tags: [
      "food",
      "drink",
      "fruit",
      "vegetable",
      "meat",
      "dessert",
      "beverage",
      "cooking",
      "restaurant",
      "cuisine",
    ],
  },

  // Travel & Places
  travel: {
    emojis: [
      "🌍",
      "🌎",
      "🌏",
      "🌐",
      "🗺️",
      "🧭",
      "🏔️",
      "⛰️",
      "🌋",
      "🗻",
      "🏕️",
      "🏖️",
      "🏜️",
      "🏝️",
      "🏞️",
      "🏟️",
      "🏛️",
      "🏗️",
      "🧱",
      "🪨",
      "🪵",
      "🛖",
      "🏘️",
      "🏚️",
      "🏠",
      "🏡",
      "🏢",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏩",
      "🏪",
      "🏫",
      "🏬",
      "🏭",
      "🏯",
      "🏰",
      "🗼",
      "🗽",
      "⛪",
      "🕌",
      "🛕",
      "🕍",
      "⛩️",
      "🕋",
      "⛲",
      "⛺",
      "🌁",
      "🌃",
      "🏙️",
      "🌄",
      "🌅",
      "🌆",
      "🌇",
      "🌉",
      "♨️",
      "🎠",
      "🎡",
      "🎢",
      "💈",
      "🎪",
      "🚂",
      "🚃",
      "🚄",
      "🚅",
      "🚆",
      "🚇",
      "🚈",
      "🚉",
      "🚊",
      "🚝",
      "🚞",
      "🚋",
      "🚌",
      "🚍",
      "🚎",
      "🚐",
      "🚑",
      "🚒",
      "🚓",
      "🚔",
      "🚕",
      "🚖",
      "🚗",
      "🚘",
      "🚙",
      "🛻",
      "🚚",
      "🚛",
      "🚜",
      "🏎️",
      "🏍️",
      "🛵",
      "🦽",
      "🦼",
      "🛺",
      "🚲",
      "🛴",
      "🛹",
      "🛼",
      "🚁",
      "🛸",
      "✈️",
      "🛩️",
      "🛫",
      "🛬",
      "🪂",
      "⛵",
      "🚤",
      "🛥️",
      "🛳️",
      "⛴️",
      "🚢",
      "⚓",
      "⛽",
      "🚧",
      "🚨",
      "🚥",
      "🚦",
      "🛑",
      "🚏",
    ],
    tags: [
      "travel",
      "transport",
      "vehicle",
      "building",
      "place",
      "landmark",
      "city",
      "nature",
      "geography",
    ],
  },

  // Activities & Sports
  activities: {
    emojis: [
      "⚽",
      "🏀",
      "🏈",
      "⚾",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🥏",
      "🎱",
      "🪀",
      "🏓",
      "🏸",
      "🏒",
      "🏑",
      "🥍",
      "🏏",
      "🪃",
      "🥅",
      "⛳",
      "🪁",
      "🏹",
      "🎣",
      "🤿",
      "🥊",
      "🥋",
      "🎽",
      "🛹",
      "🛷",
      "⛸️",
      "🥌",
      "🎿",
      "⛷️",
      "🏂",
      "🪂",
      "🏋️",
      "🤸",
      "🤼",
      "🤽",
      "🤾",
      "🤹",
      "🧘",
      "🎭",
      "🩰",
      "🎨",
      "🎬",
      "🎤",
      "🎧",
      "🎼",
      "🎵",
      "🎶",
      "🥇",
      "🥈",
      "🥉",
      "🏆",
      "🏅",
      "🎖️",
      "🎗️",
      "🎫",
      "🎟️",
      "🎪",
      "🤹",
      "🎨",
      "🎬",
      "🎤",
      "🎧",
      "🎼",
      "🎵",
      "🎶",
      "🎹",
      "🥁",
      "🪘",
      "🎷",
      "🎺",
      "🪗",
      "🎸",
      "🪕",
      "🎻",
      "🎲",
      "♠️",
      "♥️",
      "♦️",
      "♣️",
      "♟️",
      "🃏",
      "🀄",
      "🎴",
      "🎮",
      "🕹️",
      "🎯",
    ],
    tags: [
      "sport",
      "activity",
      "game",
      "music",
      "art",
      "entertainment",
      "competition",
      "hobby",
    ],
  },

  // Objects & Symbols
  objects: {
    emojis: [
      "⌚",
      "📱",
      "📲",
      "💻",
      "⌨️",
      "🖥️",
      "🖨️",
      "🖱️",
      "🖲️",
      "🕹️",
      "🗜️",
      "💽",
      "💾",
      "💿",
      "📀",
      "📼",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽️",
      "🎞️",
      "📞",
      "☎️",
      "📟",
      "📠",
      "📺",
      "📻",
      "🎙️",
      "🎚️",
      "🎛️",
      "🧭",
      "⏱️",
      "⏲️",
      "⏰",
      "🕰️",
      "⌛",
      "⏳",
      "📡",
      "🔋",
      "🪫",
      "🔌",
      "💡",
      "🔦",
      "🕯️",
      "🪔",
      "🧯",
      "🛢️",
      "💸",
      "💵",
      "💴",
      "💶",
      "💷",
      "🪙",
      "💰",
      "💳",
      "💎",
      "⚖️",
      "🪜",
      "🧰",
      "🪛",
      "🔧",
      "🔨",
      "⚒️",
      "🛠️",
      "⛏️",
      "🪚",
      "🔩",
      "⚙️",
      "🪤",
      "🧱",
      "⛓️",
      "🧲",
      "🔫",
      "💣",
      "🧨",
      "🪓",
      "🔪",
      "🗡️",
      "⚔️",
      "🛡️",
      "🚬",
      "⚰️",
      "🪦",
      "⚱️",
      "🏺",
      "🔮",
      "📿",
      "🧿",
      "💈",
      "⚗️",
      "🔭",
      "🔬",
      "🕳️",
      "🩹",
      "🩺",
      "💊",
      "💉",
      "🩸",
      "🧬",
      "🦠",
      "🧫",
      "🧪",
      "🌡️",
      "🧹",
      "🪠",
      "🧽",
      "🧴",
      "🛎️",
      "🔑",
      "🗝️",
      "🚪",
    ],
    tags: [
      "object",
      "technology",
      "tool",
      "medical",
      "household",
      "weapon",
      "money",
      "jewelry",
    ],
  },

  // Symbols & Flags
  symbols: {
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "☮️",
      "✝️",
      "☪️",
      "🕉️",
      "☸️",
      "✡️",
      "🔯",
      "🕎",
      "☯️",
      "☦️",
      "🛐",
      "⛎",
      "♈",
      "♉",
      "♊",
      "♋",
      "♌",
      "♍",
      "♎",
      "♏",
      "♐",
      "♑",
      "♒",
      "♓",
      "🆔",
      "⚛️",
      "🉑",
      "☢️",
      "☣️",
      "📴",
      "📳",
      "🈶",
      "🈚",
      "🈸",
      "🈺",
      "🈷️",
      "✴️",
      "🆚",
      "💮",
      "🉐",
      "㊙️",
      "㊗️",
      "🈴",
      "🈵",
      "🈹",
      "🈲",
      "🅰️",
      "🅱️",
      "🆎",
      "🆑",
      "🅾️",
      "🆘",
      "❌",
      "⭕",
      "🛑",
      "⛔",
      "📛",
      "🚫",
      "💯",
      "💢",
      "♨️",
      "🚷",
      "🚯",
      "🚳",
      "🚱",
      "🔞",
      "📵",
      "🚭",
      "❗",
      "❕",
      "❓",
      "❔",
      "‼️",
      "⁉️",
      "🔅",
      "🔆",
      "〽️",
      "⚠️",
      "🚸",
      "🔱",
      "⚜️",
      "🔰",
      "♻️",
      "✅",
      "🈯",
      "💹",
      "❇️",
      "✳️",
      "❎",
      "🌐",
      "💠",
      "Ⓜ️",
      "🌀",
      "💤",
      "🏧",
      "🚾",
      "♿",
      "🅿️",
      "🈳",
      "🈂️",
      "🛂",
      "🛃",
      "🛄",
      "🛅",
      "🚹",
      "🚺",
      "🚼",
      "⚧️",
      "🚻",
      "🚮",
      "🎦",
      "📶",
      "🈁",
      "🔣",
      "ℹ️",
      "🔤",
      "🔡",
      "🔠",
      "🆖",
      "🆗",
      "🆙",
      "🆒",
      "🆕",
      "🆓",
      "0️⃣",
      "1️⃣",
      "2️⃣",
      "3️⃣",
      "4️⃣",
      "5️⃣",
      "6️⃣",
      "7️⃣",
      "8️⃣",
      "9️⃣",
      "🔟",
    ],
    tags: [
      "symbol",
      "sign",
      "heart",
      "love",
      "religion",
      "zodiac",
      "number",
      "arrow",
      "warning",
    ],
  },

  // All Country Flags (Complete Set)
  flags: {
    emojis: [
      // North America
      "🇺🇸",
      "🇨🇦",
      "🇲🇽",
      "🇬🇹",
      "🇧🇿",
      "🇸🇻",
      "🇭🇳",
      "🇳🇮",
      "🇨🇷",
      "🇵🇦",
      "🇨🇺",
      "🇯🇲",
      "🇭🇹",
      "🇩🇴",
      "🇵🇷",
      "🇹🇹",
      "🇧🇧",
      "🇬🇩",
      "🇩🇲",
      "🇱🇨",
      "🇻🇨",
      "🇦🇬",
      "🇰🇳",
      "🇧🇸",
      "🇧🇲",
      "🇬🇱",
      "🇵🇲",
      "🇲🇫",
      "🇬🇵",
      "🇲🇶",

      // South America
      "🇧🇷",
      "🇦🇷",
      "🇨🇱",
      "🇨🇴",
      "🇵🇪",
      "🇻🇪",
      "🇪🇨",
      "🇺🇾",
      "🇵🇾",
      "🇧🇴",
      "🇬🇾",
      "🇸🇷",
      "🇬🇫",
      "🇫🇰",

      // Europe
      "🇬🇧",
      "🇮🇪",
      "🇮🇸",
      "🇳🇴",
      "🇸🇪",
      "🇩🇰",
      "🇫🇮",
      "🇪🇪",
      "🇱🇻",
      "🇱🇹",
      "🇵🇱",
      "🇩🇪",
      "🇳🇱",
      "🇧🇪",
      "🇱🇺",
      "🇫🇷",
      "🇨🇭",
      "🇦🇹",
      "🇱🇮",
      "🇲🇨",
      "🇦🇩",
      "🇪🇸",
      "🇵🇹",
      "🇮🇹",
      "🇸🇲",
      "🇻🇦",
      "🇲🇹",
      "🇸🇮",
      "🇭🇷",
      "🇧🇦",
      "🇷🇸",
      "🇲🇪",
      "🇦🇱",
      "🇲🇰",
      "🇬🇷",
      "🇧🇬",
      "🇷🇴",
      "🇲🇩",
      "🇺🇦",
      "🇧🇾",
      "🇷🇺",
      "🇨🇿",
      "🇸🇰",
      "🇭🇺",
      "🇸🇯",
      "🇫🇴",
      "🇦🇽",
      "🇬🇬",
      "🇯🇪",
      "🇮🇲",

      // Asia
      "🇨🇳",
      "🇯🇵",
      "🇰🇷",
      "🇰🇵",
      "🇲🇳",
      "🇹🇼",
      "🇭🇰",
      "🇲🇴",
      "🇹🇭",
      "🇻🇳",
      "🇱🇦",
      "🇰🇭",
      "🇲🇲",
      "🇲🇾",
      "🇸🇬",
      "🇮🇩",
      "🇧🇳",
      "🇵🇭",
      "🇹🇱",
      "🇮🇳",
      "🇵🇰",
      "🇧🇩",
      "🇱🇰",
      "🇲🇻",
      "🇳🇵",
      "🇧🇹",
      "🇦🇫",
      "🇮🇷",
      "🇮🇶",
      "🇸🇾",
      "🇯🇴",
      "🇱🇧",
      "🇮🇱",
      "🇵🇸",
      "🇸🇦",
      "🇾🇪",
      "🇴🇲",
      "🇦🇪",
      "🇶🇦",
      "🇧🇭",
      "🇰🇼",
      "🇹🇷",
      "🇨🇾",
      "🇬🇪",
      "🇦🇲",
      "🇦🇿",
      "🇰🇿",
      "🇺🇿",
      "🇰🇬",
      "🇹🇯",
      "🇹🇲",

      // Africa
      "🇪🇬",
      "🇱🇾",
      "🇹🇳",
      "🇩🇿",
      "🇲🇦",
      "🇪🇭",
      "🇸🇩",
      "🇸🇸",
      "🇪🇹",
      "🇪🇷",
      "🇩🇯",
      "🇸🇴",
      "🇰🇪",
      "🇺🇬",
      "🇷🇼",
      "🇧🇮",
      "🇹🇿",
      "🇲🇿",
      "🇲🇼",
      "🇿🇲",
      "🇿🇼",
      "🇧🇼",
      "🇳🇦",
      "🇿🇦",
      "🇱🇸",
      "🇸🇿",
      "🇲🇬",
      "🇲🇺",
      "🇸🇨",
      "🇰🇲",
      "🇾🇹",
      "🇷🇪",
      "🇦🇴",
      "🇨🇩",
      "🇨🇫",
      "🇨🇲",
      "🇹🇩",
      "🇳🇪",
      "🇳🇬",
      "🇧🇯",
      "🇹🇬",
      "🇬🇭",
      "🇧🇫",
      "🇨🇮",
      "🇱🇷",
      "🇸🇱",
      "🇬🇳",
      "🇬🇼",
      "🇸🇳",
      "🇬🇲",
      "🇲🇱",
      "🇲🇷",
      "🇨🇻",
      "🇸🇹",

      // Oceania
      "🇦🇺",
      "🇳🇿",
      "🇵🇬",
      "🇫🇯",
      "🇳🇨",
      "🇸🇧",
      "🇻🇺",
      "🇹🇴",
      "🇼🇸",
      "🇰🇮",
      "🇹🇻",
      "🇳🇷",
      "🇵🇼",
      "🇫🇲",
      "🇲🇭",
      "🇬🇺",
      "🇦🇸",
      "🇲🇵",
      "🇵🇫",
      "🇼🇫",
      "🇨🇰",
      "🇳🇺",
      "🇵🇳",
      "🇹🇰",
      "🇳🇫",
      "🇨🇽",
      "🇨🇨",
      "🇭🇲",
      "🇦🇶",

      // Other Territories & Special Flags
      "🇦🇨",
      "🇧🇻",
      "🇨🇵",
      "🇪🇦",
      "🇩🇬",
      "🇮🇴",
      "🇹🇦",
      "🇺🇳",
      "🇪🇺",
      "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
      "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
      "🏴‍☠️",
      "🏳️",
      "🏳️‍🌈",
      "🏳️‍⚧️",
      "🚩",
    ],
    tags: [
      "flag",
      "country",
      "nation",
      "geography",
      "politics",
      "culture",
      "territory",
    ],
  },

  // Weather & Nature
  weather: {
    emojis: [
      "☀️",
      "🌤️",
      "⛅",
      "🌥️",
      "☁️",
      "🌦️",
      "🌧️",
      "⛈️",
      "🌩️",
      "🌨️",
      "❄️",
      "☃️",
      "⛄",
      "🌬️",
      "💨",
      "🌪️",
      "🌫️",
      "🌊",
      "💧",
      "💦",
      "☔",
      "☂️",
      "🌈",
      "🌙",
      "🌛",
      "🌜",
      "🌚",
      "🌝",
      "🌞",
      "⭐",
      "🌟",
      "💫",
      "✨",
      "☄️",
      "🪐",
      "🌍",
      "🌎",
      "🌏",
      "🌑",
      "🌒",
      "🌓",
      "🌔",
      "🌕",
      "🌖",
      "🌗",
      "🌘",
      "🌙",
      "🔥",
      "💥",
      "⚡",
      "🌋",
    ],
    tags: [
      "weather",
      "nature",
      "sky",
      "rain",
      "sun",
      "moon",
      "stars",
      "storm",
      "snow",
      "wind",
    ],
  },

  // Plants & Nature
  plants: {
    emojis: [
      "🌱",
      "🌿",
      "☘️",
      "🍀",
      "🎍",
      "🪴",
      "🎋",
      "🍃",
      "🌾",
      "🌵",
      "🌲",
      "🌳",
      "🌴",
      "🌻",
      "🌞",
      "🌺",
      "🌸",
      "🌼",
      "🌷",
      "🥀",
      "🌹",
      "🏵️",
      "💐",
      "🌿",
      "🍄",
      "🪨",
      "🪵",
      "🦕",
      "🦖",
      "🪸",
      "🌊",
      "🏔️",
      "⛰️",
      "🗻",
      "🏕️",
      "🏖️",
      "🏜️",
      "🏝️",
      "🏞️",
    ],
    tags: [
      "plant",
      "flower",
      "tree",
      "nature",
      "garden",
      "forest",
      "mountain",
      "desert",
      "beach",
    ],
  },

  // Body Parts & Gestures
  body: {
    emojis: [
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🫰",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "🫵",
      "👍",
      "👎",
      "👊",
      "✊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "🫶",
      "👐",
      "🤲",
      "🤝",
      "🙏",
      "✍️",
      "💅",
      "🤳",
      "💪",
      "🦾",
      "🦵",
      "🦿",
      "🦶",
      "👣",
      "👂",
      "🦻",
      "👃",
      "🫀",
      "🫁",
      "🧠",
      "🦷",
      "🦴",
      "👀",
      "👁️",
      "👅",
      "👄",
      "🫦",
      "💋",
      "🩸",
    ],
    tags: [
      "hand",
      "body",
      "gesture",
      "finger",
      "arm",
      "leg",
      "face",
      "organ",
      "anatomy",
    ],
  },

  // Clothing & Fashion
  clothing: {
    emojis: [
      "👕",
      "👔",
      "👗",
      "👘",
      "🥻",
      "🩱",
      "🩲",
      "🩳",
      "👖",
      "👚",
      "👛",
      "👜",
      "👝",
      "🎒",
      "👞",
      "👟",
      "🥾",
      "🥿",
      "👠",
      "👡",
      "🩴",
      "👢",
      "👑",
      "👒",
      "🎩",
      "🎓",
      "🧢",
      "🪖",
      "⛑️",
      "📿",
      "💄",
      "💍",
      "💎",
      "🔇",
      "🔈",
      "🔉",
      "🔊",
      "📢",
      "📣",
      "📯",
      "🔔",
      "🔕",
      "🎵",
      "🎶",
      "🎤",
      "🎧",
      "📻",
      "🎷",
      "🪗",
      "🎸",
      "🎹",
      "🎺",
      "🎻",
      "🪕",
      "🥁",
      "🪘",
      "🎬",
      "🎭",
    ],
    tags: [
      "clothing",
      "fashion",
      "accessories",
      "shoes",
      "hat",
      "jewelry",
      "makeup",
    ],
  },

  // Transportation Extended
  transport: {
    emojis: [
      "🚗",
      "🚕",
      "🚙",
      "🚌",
      "🚎",
      "🏎️",
      "🚓",
      "🚑",
      "🚒",
      "🚐",
      "🛻",
      "🚚",
      "🚛",
      "🚜",
      "🏍️",
      "🛵",
      "🚲",
      "🛴",
      "🛹",
      "🛼",
      "🚁",
      "🛸",
      "✈️",
      "🛩️",
      "🛫",
      "🛬",
      "🪂",
      "💺",
      "🚀",
      "🛰️",
      "🚉",
      "🚞",
      "🚝",
      "🚄",
      "🚅",
      "🚈",
      "🚂",
      "🚆",
      "🚇",
      "🚊",
      "🚋",
      "🚃",
      "🚟",
      "🚠",
      "🚡",
      "⛴️",
      "🛥️",
      "🚤",
      "⛵",
      "🛶",
      "🚣",
      "🛟",
      "⚓",
      "🪝",
      "⛽",
      "🚧",
      "🚨",
      "🚥",
      "🚦",
      "🛑",
      "🚏",
      "🗺️",
      "🗿",
      "🗽",
      "🗼",
      "🏰",
      "🏯",
      "🏟️",
      "🎡",
      "🎢",
      "🎠",
      "⛲",
      "⛱️",
      "🏖️",
      "🏕️",
      "⛺",
      "🏠",
      "🏡",
      "🏘️",
      "🏚️",
      "🏗️",
      "🏭",
      "🏢",
      "🏬",
      "🏣",
      "🏤",
      "🏥",
      "🏦",
      "🏨",
      "🏪",
      "🏫",
      "🏩",
      "💒",
      "🏛️",
      "⛪",
      "🕌",
      "🕍",
      "🛕",
      "🕋",
      "⛩️",
    ],
    tags: [
      "transport",
      "vehicle",
      "car",
      "plane",
      "train",
      "ship",
      "bike",
      "building",
      "architecture",
    ],
  },
};

// Create flat categories for the UI
const EMOJI_CATEGORIES = {
  popular: [
    "😀",
    "❤️",
    "😂",
    "👍",
    "😊",
    "🔥",
    "💯",
    "✨",
    "🎉",
    "👏",
    "🙌",
    "💪",
    "🌍",
    "🍕",
    "🎭",
    "☀️",
    "🌈",
    "🎵",
    "🏠",
    "✈️",
    "🚗",
    "📱",
    "💡",
    "🎮",
    "⚽",
  ],
  faces: EMOJI_DATABASE.faces.emojis,
  people: EMOJI_DATABASE.people.emojis,
  animals: EMOJI_DATABASE.animals.emojis,
  food: EMOJI_DATABASE.food.emojis,
  travel: EMOJI_DATABASE.travel.emojis,
  activities: EMOJI_DATABASE.activities.emojis,
  objects: EMOJI_DATABASE.objects.emojis,
  symbols: EMOJI_DATABASE.symbols.emojis,
  flags: EMOJI_DATABASE.flags.emojis,
  weather: EMOJI_DATABASE.weather.emojis,
  plants: EMOJI_DATABASE.plants.emojis,
  body: EMOJI_DATABASE.body.emojis,
  clothing: EMOJI_DATABASE.clothing.emojis,
  transport: EMOJI_DATABASE.transport.emojis,
};

function EmojiModal({ onAddEmoji, onClose, isLoading = false }) {
  const [selectedEmoji, setSelectedEmoji] = useState("");
  const [searchTerm, setSearchTerm] = useState("");
  const [filteredEmojis, setFilteredEmojis] = useState([]);
  const [activeCategory, setActiveCategory] = useState("popular");

  // Flatten all emojis for searching
  const allEmojis = Object.values(EMOJI_DATABASE).flatMap(
    (category) => category.emojis
  );

  useEffect(() => {
    if (searchTerm.trim()) {
      const searchLower = searchTerm.toLowerCase();
      const filtered = [];

      // Search through all categories and their tags
      Object.values(EMOJI_DATABASE).forEach((category) => {
        category.emojis.forEach((emoji) => {
          // Check if emoji matches search term or any of the category tags
          const matchesTags = category.tags.some((tag) =>
            tag.toLowerCase().includes(searchLower)
          );

          // Check if search term matches specific emoji keywords
          const matchesKeywords = getEmojiKeywords(emoji).some((keyword) =>
            keyword.toLowerCase().includes(searchLower)
          );

          if (matchesTags || matchesKeywords || emoji.includes(searchTerm)) {
            if (!filtered.includes(emoji)) {
              filtered.push(emoji);
            }
          }
        });
      });

      setFilteredEmojis(filtered);
    } else {
      setFilteredEmojis(EMOJI_CATEGORIES[activeCategory]);
    }
  }, [searchTerm, activeCategory]);

  // Comprehensive emoji keywords mapping for better search
  const getEmojiKeywords = (emoji) => {
    const keywords = {
      // Faces
      "😀": ["happy", "smile", "grin", "joy", "cheerful"],
      "😂": ["laugh", "funny", "tears", "joy", "lol", "hilarious"],
      "😊": ["happy", "smile", "blush", "pleased", "content"],
      "😍": ["love", "heart eyes", "adore", "crush", "infatuated"],
      "😢": ["sad", "cry", "tear", "upset", "sorrow"],
      "😡": ["angry", "mad", "rage", "furious", "upset"],
      "😴": ["sleep", "tired", "zzz", "sleepy", "rest"],
      "🤔": ["think", "wonder", "consider", "ponder", "hmm"],

      // Food
      "🍕": ["pizza", "italian", "cheese", "pepperoni", "slice"],
      "🍔": ["burger", "hamburger", "american", "fast food", "beef"],
      "🍟": ["fries", "chips", "potato", "fast food", "golden"],
      "🍣": ["sushi", "japanese", "fish", "raw", "rice"],
      "🍝": ["pasta", "italian", "spaghetti", "noodles", "sauce"],
      "🍎": ["apple", "fruit", "red", "healthy", "crisp"],
      "🍌": ["banana", "fruit", "yellow", "potassium", "tropical"],
      "🍰": ["cake", "dessert", "sweet", "birthday", "celebration"],
      "☕": ["coffee", "drink", "caffeine", "morning", "hot"],
      "🍺": ["beer", "drink", "alcohol", "pub", "golden"],

      // Animals
      "🐶": ["dog", "puppy", "pet", "loyal", "cute"],
      "🐱": ["cat", "kitten", "pet", "meow", "feline"],
      "🦁": ["lion", "king", "brave", "mane", "africa"],
      "🐘": ["elephant", "big", "trunk", "africa", "memory"],
      "🦘": ["kangaroo", "australia", "hop", "pouch", "joey"],
      "🐧": ["penguin", "antarctica", "ice", "cold", "waddle"],
      "🦋": ["butterfly", "beautiful", "transformation", "colorful", "fly"],
      "🐝": ["bee", "honey", "buzz", "yellow", "pollinate"],

      // Travel
      "✈️": ["plane", "airplane", "travel", "flight", "sky"],
      "🚗": ["car", "drive", "vehicle", "transport", "road"],
      "🚢": ["ship", "boat", "ocean", "cruise", "sail"],
      "🏔️": ["mountain", "peak", "snow", "high", "climb"],
      "🏖️": ["beach", "sand", "ocean", "vacation", "sun"],
      "🏰": ["castle", "medieval", "princess", "fortress", "royal"],
      "🗽": ["statue of liberty", "new york", "america", "freedom", "torch"],
      "🌍": ["earth", "world", "globe", "planet", "international"],

      // Activities
      "⚽": ["soccer", "football", "sport", "ball", "kick"],
      "🏀": ["basketball", "sport", "hoop", "dribble", "orange"],
      "🎮": ["gaming", "video game", "controller", "play", "fun"],
      "🎵": ["music", "note", "song", "melody", "sound"],
      "🎨": ["art", "paint", "creative", "palette", "artist"],
      "📚": ["books", "study", "read", "learn", "education"],

      // Symbols
      "❤️": ["love", "heart", "red", "romance", "affection"],
      "💯": ["hundred", "perfect", "score", "excellent", "full"],
      "🔥": ["fire", "hot", "flame", "burn", "lit"],
      "✨": ["sparkle", "magic", "shine", "glitter", "special"],
      "🎉": ["party", "celebration", "confetti", "fun", "festive"],
      "👍": ["thumbs up", "good", "approve", "like", "yes"],
      "💪": ["strong", "muscle", "power", "strength", "flex"],

      // Weather
      "☀️": ["sun", "sunny", "bright", "hot", "warm", "clear"],
      "🌧️": ["rain", "rainy", "wet", "storm", "weather"],
      "❄️": ["snow", "cold", "winter", "ice", "frozen"],
      "⛅": ["cloudy", "clouds", "partly cloudy", "overcast"],
      "🌈": ["rainbow", "colorful", "pride", "after rain"],
      "⚡": ["lightning", "thunder", "storm", "electric", "power"],
      "🌪️": ["tornado", "hurricane", "cyclone", "wind", "disaster"],
      "🌊": ["wave", "ocean", "sea", "tsunami", "water"],

      // Plants & Nature
      "🌸": ["cherry blossom", "spring", "pink", "japan", "flower"],
      "🌻": ["sunflower", "yellow", "summer", "bright", "happy"],
      "🌹": ["rose", "red", "love", "romance", "valentine"],
      "🌵": ["cactus", "desert", "green", "prickly", "arizona"],
      "🌲": ["evergreen", "pine", "christmas", "forest", "green"],
      "🍄": ["mushroom", "fungi", "forest", "red", "mario"],

      // Body & Gestures
      "👋": ["wave", "hello", "goodbye", "hi", "greeting"],
      "👍": ["thumbs up", "good", "approve", "like", "yes"],
      "👎": ["thumbs down", "bad", "disapprove", "dislike", "no"],
      "🤝": ["handshake", "deal", "agreement", "partnership", "meeting"],
      "🙏": ["pray", "please", "thank you", "namaste", "hope"],
      "💪": ["muscle", "strong", "power", "flex", "strength"],

      // Clothing
      "👕": ["shirt", "tshirt", "clothing", "casual", "wear"],
      "👗": ["dress", "formal", "elegant", "woman", "fashion"],
      "👠": ["high heels", "shoes", "formal", "elegant", "woman"],
      "👑": ["crown", "royal", "king", "queen", "luxury"],
      "🎩": ["top hat", "formal", "gentleman", "magic", "elegant"],

      // Countries/Flags (Extended)
      "🇺🇸": ["usa", "america", "united states", "american", "stars stripes"],
      "🇬🇧": ["uk", "britain", "england", "british", "union jack"],
      "🇫🇷": ["france", "french", "paris", "tricolor", "blue white red"],
      "🇩🇪": ["germany", "german", "berlin", "black red yellow"],
      "🇯🇵": ["japan", "japanese", "tokyo", "rising sun"],
      "🇮🇹": ["italy", "italian", "rome", "green white red"],
      "🇨🇦": ["canada", "canadian", "maple leaf", "red white"],
      "🇦🇺": ["australia", "australian", "sydney", "melbourne"],
      "🇧🇷": ["brazil", "brazilian", "rio", "green yellow"],
      "🇲🇽": ["mexico", "mexican", "green white red"],
      "🇮🇳": ["india", "indian", "delhi", "mumbai", "saffron white green"],
      "🇨🇳": ["china", "chinese", "beijing", "red yellow"],
      "🇪🇸": ["spain", "spanish", "madrid", "red yellow"],
      "🇳🇱": ["netherlands", "dutch", "amsterdam", "orange"],
      "🇸🇪": ["sweden", "swedish", "stockholm", "blue yellow"],
      "🇳🇴": ["norway", "norwegian", "oslo", "blue red white"],
      "🇩🇰": ["denmark", "danish", "copenhagen", "red white"],
      "🇫🇮": ["finland", "finnish", "helsinki", "blue white"],
      "🇷🇺": ["russia", "russian", "moscow", "red blue white"],
      "🇰🇷": ["south korea", "korean", "seoul", "red blue"],
      "🇹🇭": ["thailand", "thai", "bangkok", "red white blue"],
      "🇻🇳": ["vietnam", "vietnamese", "hanoi", "red yellow"],
      "🇸🇬": ["singapore", "singaporean", "red white"],
      "🇮🇩": ["indonesia", "indonesian", "jakarta", "red white"],
      "🇵🇭": ["philippines", "filipino", "manila", "blue red"],
      "🇦🇷": ["argentina", "argentinian", "buenos aires", "blue white"],
      "🇨🇱": ["chile", "chilean", "santiago", "red white blue"],
      "🇨🇴": ["colombia", "colombian", "bogota", "yellow blue red"],
      "🇵🇪": ["peru", "peruvian", "lima", "red white"],
      "🇻🇪": ["venezuela", "venezuelan", "caracas", "yellow blue red"],
      "🇪🇨": ["ecuador", "ecuadorian", "quito", "yellow blue red"],
      "🇺🇾": ["uruguay", "uruguayan", "montevideo", "blue white"],
      "🇵🇾": ["paraguay", "paraguayan", "asuncion", "red white blue"],
      "🇧🇴": ["bolivia", "bolivian", "la paz", "red yellow green"],
      "🇿🇦": ["south africa", "south african", "cape town", "colorful"],
      "🇪🇬": ["egypt", "egyptian", "cairo", "red white black"],
      "🇳🇬": ["nigeria", "nigerian", "lagos", "green white"],
      "🇰🇪": ["kenya", "kenyan", "nairobi", "black red green"],
      "🇪🇹": ["ethiopia", "ethiopian", "addis ababa", "green yellow red"],
      "🇬🇭": ["ghana", "ghanaian", "accra", "red yellow green"],
      "🇲🇦": ["morocco", "moroccan", "rabat", "red green"],
      "🇹🇳": ["tunisia", "tunisian", "tunis", "red white"],
      "🇩🇿": ["algeria", "algerian", "algiers", "green white"],
    };
    return keywords[emoji] || [];
  };

  const handleSubmit = () => {
    if (selectedEmoji) {
      onAddEmoji(selectedEmoji);
    }
  };

  const handleBackdropClick = (e) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  return (
    <div className="emoji-modal" onClick={handleBackdropClick}>
      <div className="emoji-modal-content">
        <h3>🎯 Add an Emoji</h3>

        <input
          type="text"
          placeholder="Search emojis... (e.g., 'pizza', 'happy', 'japan', 'travel')"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="emoji-search"
          autoFocus
        />

        {!searchTerm && (
          <div style={{ marginBottom: "15px" }}>
            {Object.keys(EMOJI_CATEGORIES).map((category) => (
              <button
                key={category}
                onClick={() => setActiveCategory(category)}
                style={{
                  margin: "2px",
                  padding: "5px 10px",
                  border: "none",
                  borderRadius: "15px",
                  backgroundColor:
                    activeCategory === category ? "#3388ff" : "#f0f0f0",
                  color: activeCategory === category ? "white" : "#333",
                  cursor: "pointer",
                  fontSize: "12px",
                  textTransform: "capitalize",
                }}
              >
                {category}
              </button>
            ))}
          </div>
        )}

        <div className="emoji-grid">
          {filteredEmojis.map((emoji, index) => (
            <button
              key={`${emoji}-${index}`}
              className={`emoji-option ${
                selectedEmoji === emoji ? "selected" : ""
              }`}
              onClick={() => setSelectedEmoji(emoji)}
            >
              {emoji}
            </button>
          ))}
        </div>

        {filteredEmojis.length === 0 && searchTerm && (
          <p style={{ textAlign: "center", color: "#666", margin: "20px 0" }}>
            No emojis found for "{searchTerm}"
          </p>
        )}

        <div className="modal-buttons">
          <button className="btn btn-secondary" onClick={onClose}>
            Cancel
          </button>
          <button
            className="btn btn-primary"
            onClick={handleSubmit}
            disabled={!selectedEmoji || isLoading}
          >
            {isLoading ? "Adding..." : `Add ${selectedEmoji}`}
          </button>
        </div>
      </div>
    </div>
  );
}

export default EmojiModal;
